name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: ramblings of an insane mind JOIN
        env:
          JOIN: ${{ join(github.event.commits.*.message, ', ') }}
        run: echo "$JOIN"

      - name: ramblings of an insane mind CONTAINS part deux
        env:
          CONTAINS: ${{ !contains(join(github.event.commits.*.message, ', '), '#') }}
        run: echo "$CONTAINS"
